version: '3.8'
services:
  authen-db:
    image: postgres:latest
    container_name: authen_db
    environment:
        POSTGRES_USER: user_authen_db
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: authen_service_db
    ports:
        - "5433:5432"
    volumes:
        - ./docker/postgres/init-database-test.sql:/docker-entrypoint-initdb.d/init-database-test.sql

  authen-redis:
    container_name: authen_redis
    image: redis:5.0.6
    ports:
      - "6379:6379"
