app:
  datasource:
    driver: postgres
    host: localhost
    port: 5433
    database: authen_service_db
    username: user_authen_db
    password: secret
  redis:
    host: localhost
    port: 6379
  logging:
    development: true
  security:
    http:
      jwt.publicKey: ${JWT_PUBLIC_KEY}
