app:
  datasource:
    driver: postgres
    host: ${POSTGRES_HOST}
    port: 5432
    database: ${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: 6379
  logging:
    development: true
  security:
    http:
      jwt.publicKey: ${JWT_PUBLIC_KEY}
  services:
    notification-service:
      BaseUrl: https://api.courier.com
      Token: ${NOTIFICATION_SERVICE_TOKEN}
      TemplateOTPForRegistration: QJS1DXW1X2MTZHJGM0E4GGZP8VS8
    security:
      http:
        jwt:
          PrivateKey: ${JWT_PRIVATE_KEY}
          TokenExpired: 86400
          RefreshTokenExpired: 86400
