name: Build and Push Docker Images

on:
  push:
    branches:
      - master           # Trigger on the `master` branch
      - feature/**       # Trigger on any branch under `feature/`
      - release/**       # Trigger on any branch under `release/`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (or another registry)
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and Push Public Service Image
      - name: Build and Push Public Service
        uses: docker/build-push-action@v5
        with:
          context: ./                        # Change context to root of repository
          dockerfile: ./devops/docker/Dockerfile-public  # Provide path relative to repository root
          push: true
          tags: khaihust/auth-public-service:latest

      # Step 5: Build and Push Migration Service Image
      - name: Build and Push Migration Service
        uses: docker/build-push-action@v5
        with:
          context: ./                         # Change context to root of repository
          dockerfile: ./devops/docker/Dockerfile-migration  # Provide path relative to repository root
          push: true
          tags: khaihust/auth-migration-service:latest
