name: Deploy to GCE Instance

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions UI

jobs:
  deploy:
    permissions:
      contents: 'read'    # Required for actions/checkout
      id-token: 'write'   # Required for Workload Identity Federation

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - uses: 'actions/checkout@v4'

      # Step 2: Authenticate with GCP
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

      # Step 3: SSH into the Compute Engine Instance
      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v1'
        with:
          instance_name: 'server-instance-cp'
          zone: 'asia-east1-a'
          ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
          command: |
            # Pull Docker image
            docker pull ${{ secrets.DOCKER_IMAGE }}
            
            # Stop and remove existing container
            docker stop my-app || true
            docker rm my-app || true
            
            # Run the updated container
            docker run -d --name my-app -p 8080:8080 gcr.io/my-project/my-app:latest

      # Step 4: Output Logs
      - id: 'log-output'
        run: |-
          echo 'STDOUT: ${{ steps.compute-ssh.outputs.stdout }}'
          echo 'STDERR: ${{ steps.compute-ssh.outputs.stderr }}'
